/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pe.gob.congreso.pl.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Documento extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2840956690977998042L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Documento\",\"namespace\":\"pe.gob.congreso.pl.data\",\"fields\":[{\"name\":\"titulo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"tipo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"enlace\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"fecha\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Documento> ENCODER =
      new BinaryMessageEncoder<Documento>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Documento> DECODER =
      new BinaryMessageDecoder<Documento>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Documento> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Documento> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Documento> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Documento>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Documento to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Documento from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Documento instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Documento fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String titulo;
   private java.lang.String tipo;
   private java.lang.String enlace;
   private java.lang.Long fecha;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Documento() {}

  /**
   * All-args constructor.
   * @param titulo The new value for titulo
   * @param tipo The new value for tipo
   * @param enlace The new value for enlace
   * @param fecha The new value for fecha
   */
  public Documento(java.lang.String titulo, java.lang.String tipo, java.lang.String enlace, java.lang.Long fecha) {
    this.titulo = titulo;
    this.tipo = tipo;
    this.enlace = enlace;
    this.fecha = fecha;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return titulo;
    case 1: return tipo;
    case 2: return enlace;
    case 3: return fecha;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: titulo = value$ != null ? value$.toString() : null; break;
    case 1: tipo = value$ != null ? value$.toString() : null; break;
    case 2: enlace = value$ != null ? value$.toString() : null; break;
    case 3: fecha = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'titulo' field.
   * @return The value of the 'titulo' field.
   */
  public java.lang.String getTitulo() {
    return titulo;
  }


  /**
   * Sets the value of the 'titulo' field.
   * @param value the value to set.
   */
  public void setTitulo(java.lang.String value) {
    this.titulo = value;
  }

  /**
   * Gets the value of the 'tipo' field.
   * @return The value of the 'tipo' field.
   */
  public java.lang.String getTipo() {
    return tipo;
  }


  /**
   * Sets the value of the 'tipo' field.
   * @param value the value to set.
   */
  public void setTipo(java.lang.String value) {
    this.tipo = value;
  }

  /**
   * Gets the value of the 'enlace' field.
   * @return The value of the 'enlace' field.
   */
  public java.lang.String getEnlace() {
    return enlace;
  }


  /**
   * Sets the value of the 'enlace' field.
   * @param value the value to set.
   */
  public void setEnlace(java.lang.String value) {
    this.enlace = value;
  }

  /**
   * Gets the value of the 'fecha' field.
   * @return The value of the 'fecha' field.
   */
  public java.lang.Long getFecha() {
    return fecha;
  }


  /**
   * Sets the value of the 'fecha' field.
   * @param value the value to set.
   */
  public void setFecha(java.lang.Long value) {
    this.fecha = value;
  }

  /**
   * Creates a new Documento RecordBuilder.
   * @return A new Documento RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Documento.Builder newBuilder() {
    return new pe.gob.congreso.pl.data.Documento.Builder();
  }

  /**
   * Creates a new Documento RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Documento RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Documento.Builder newBuilder(pe.gob.congreso.pl.data.Documento.Builder other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Documento.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Documento.Builder(other);
    }
  }

  /**
   * Creates a new Documento RecordBuilder by copying an existing Documento instance.
   * @param other The existing instance to copy.
   * @return A new Documento RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Documento.Builder newBuilder(pe.gob.congreso.pl.data.Documento other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Documento.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Documento.Builder(other);
    }
  }

  /**
   * RecordBuilder for Documento instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Documento>
    implements org.apache.avro.data.RecordBuilder<Documento> {

    private java.lang.String titulo;
    private java.lang.String tipo;
    private java.lang.String enlace;
    private java.lang.Long fecha;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Documento.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.titulo)) {
        this.titulo = data().deepCopy(fields()[0].schema(), other.titulo);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tipo)) {
        this.tipo = data().deepCopy(fields()[1].schema(), other.tipo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.enlace)) {
        this.enlace = data().deepCopy(fields()[2].schema(), other.enlace);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.fecha)) {
        this.fecha = data().deepCopy(fields()[3].schema(), other.fecha);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Documento instance
     * @param other The existing instance to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Documento other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.titulo)) {
        this.titulo = data().deepCopy(fields()[0].schema(), other.titulo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tipo)) {
        this.tipo = data().deepCopy(fields()[1].schema(), other.tipo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enlace)) {
        this.enlace = data().deepCopy(fields()[2].schema(), other.enlace);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fecha)) {
        this.fecha = data().deepCopy(fields()[3].schema(), other.fecha);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'titulo' field.
      * @return The value.
      */
    public java.lang.String getTitulo() {
      return titulo;
    }


    /**
      * Sets the value of the 'titulo' field.
      * @param value The value of 'titulo'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder setTitulo(java.lang.String value) {
      validate(fields()[0], value);
      this.titulo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'titulo' field has been set.
      * @return True if the 'titulo' field has been set, false otherwise.
      */
    public boolean hasTitulo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'titulo' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder clearTitulo() {
      titulo = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipo' field.
      * @return The value.
      */
    public java.lang.String getTipo() {
      return tipo;
    }


    /**
      * Sets the value of the 'tipo' field.
      * @param value The value of 'tipo'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder setTipo(java.lang.String value) {
      validate(fields()[1], value);
      this.tipo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo' field has been set.
      * @return True if the 'tipo' field has been set, false otherwise.
      */
    public boolean hasTipo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tipo' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder clearTipo() {
      tipo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'enlace' field.
      * @return The value.
      */
    public java.lang.String getEnlace() {
      return enlace;
    }


    /**
      * Sets the value of the 'enlace' field.
      * @param value The value of 'enlace'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder setEnlace(java.lang.String value) {
      validate(fields()[2], value);
      this.enlace = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'enlace' field has been set.
      * @return True if the 'enlace' field has been set, false otherwise.
      */
    public boolean hasEnlace() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'enlace' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder clearEnlace() {
      enlace = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fecha' field.
      * @return The value.
      */
    public java.lang.Long getFecha() {
      return fecha;
    }


    /**
      * Sets the value of the 'fecha' field.
      * @param value The value of 'fecha'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder setFecha(java.lang.Long value) {
      validate(fields()[3], value);
      this.fecha = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fecha' field has been set.
      * @return True if the 'fecha' field has been set, false otherwise.
      */
    public boolean hasFecha() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fecha' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Documento.Builder clearFecha() {
      fecha = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Documento build() {
      try {
        Documento record = new Documento();
        record.titulo = fieldSetFlags()[0] ? this.titulo : (java.lang.String) defaultValue(fields()[0]);
        record.tipo = fieldSetFlags()[1] ? this.tipo : (java.lang.String) defaultValue(fields()[1]);
        record.enlace = fieldSetFlags()[2] ? this.enlace : (java.lang.String) defaultValue(fields()[2]);
        record.fecha = fieldSetFlags()[3] ? this.fecha : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Documento>
    WRITER$ = (org.apache.avro.io.DatumWriter<Documento>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Documento>
    READER$ = (org.apache.avro.io.DatumReader<Documento>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.titulo == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.titulo);
    }

    if (this.tipo == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.tipo);
    }

    out.writeString(this.enlace);

    if (this.fecha == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeLong(this.fecha);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 0) {
        in.readNull();
        this.titulo = null;
      } else {
        this.titulo = in.readString();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.tipo = null;
      } else {
        this.tipo = in.readString();
      }

      this.enlace = in.readString();

      if (in.readIndex() != 0) {
        in.readNull();
        this.fecha = null;
      } else {
        this.fecha = in.readLong();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 0) {
            in.readNull();
            this.titulo = null;
          } else {
            this.titulo = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.tipo = null;
          } else {
            this.tipo = in.readString();
          }
          break;

        case 2:
          this.enlace = in.readString();
          break;

        case 3:
          if (in.readIndex() != 0) {
            in.readNull();
            this.fecha = null;
          } else {
            this.fecha = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










