/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pe.gob.congreso.pl.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Expediente extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1781026071870995084L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Expediente\",\"namespace\":\"pe.gob.congreso.pl.data\",\"fields\":[{\"name\":\"titulo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"subtitulo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"documentos\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Documento\",\"fields\":[{\"name\":\"titulo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"tipo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"enlace\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"fecha\",\"type\":[\"long\",\"null\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Expediente> ENCODER =
      new BinaryMessageEncoder<Expediente>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Expediente> DECODER =
      new BinaryMessageDecoder<Expediente>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Expediente> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Expediente> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Expediente> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Expediente>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Expediente to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Expediente from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Expediente instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Expediente fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String titulo;
   private java.lang.String subtitulo;
   private java.util.List<pe.gob.congreso.pl.data.Documento> documentos;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Expediente() {}

  /**
   * All-args constructor.
   * @param titulo The new value for titulo
   * @param subtitulo The new value for subtitulo
   * @param documentos The new value for documentos
   */
  public Expediente(java.lang.String titulo, java.lang.String subtitulo, java.util.List<pe.gob.congreso.pl.data.Documento> documentos) {
    this.titulo = titulo;
    this.subtitulo = subtitulo;
    this.documentos = documentos;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return titulo;
    case 1: return subtitulo;
    case 2: return documentos;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: titulo = value$ != null ? value$.toString() : null; break;
    case 1: subtitulo = value$ != null ? value$.toString() : null; break;
    case 2: documentos = (java.util.List<pe.gob.congreso.pl.data.Documento>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'titulo' field.
   * @return The value of the 'titulo' field.
   */
  public java.lang.String getTitulo() {
    return titulo;
  }


  /**
   * Sets the value of the 'titulo' field.
   * @param value the value to set.
   */
  public void setTitulo(java.lang.String value) {
    this.titulo = value;
  }

  /**
   * Gets the value of the 'subtitulo' field.
   * @return The value of the 'subtitulo' field.
   */
  public java.lang.String getSubtitulo() {
    return subtitulo;
  }


  /**
   * Sets the value of the 'subtitulo' field.
   * @param value the value to set.
   */
  public void setSubtitulo(java.lang.String value) {
    this.subtitulo = value;
  }

  /**
   * Gets the value of the 'documentos' field.
   * @return The value of the 'documentos' field.
   */
  public java.util.List<pe.gob.congreso.pl.data.Documento> getDocumentos() {
    return documentos;
  }


  /**
   * Sets the value of the 'documentos' field.
   * @param value the value to set.
   */
  public void setDocumentos(java.util.List<pe.gob.congreso.pl.data.Documento> value) {
    this.documentos = value;
  }

  /**
   * Creates a new Expediente RecordBuilder.
   * @return A new Expediente RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Expediente.Builder newBuilder() {
    return new pe.gob.congreso.pl.data.Expediente.Builder();
  }

  /**
   * Creates a new Expediente RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Expediente RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Expediente.Builder newBuilder(pe.gob.congreso.pl.data.Expediente.Builder other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Expediente.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Expediente.Builder(other);
    }
  }

  /**
   * Creates a new Expediente RecordBuilder by copying an existing Expediente instance.
   * @param other The existing instance to copy.
   * @return A new Expediente RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Expediente.Builder newBuilder(pe.gob.congreso.pl.data.Expediente other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Expediente.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Expediente.Builder(other);
    }
  }

  /**
   * RecordBuilder for Expediente instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Expediente>
    implements org.apache.avro.data.RecordBuilder<Expediente> {

    private java.lang.String titulo;
    private java.lang.String subtitulo;
    private java.util.List<pe.gob.congreso.pl.data.Documento> documentos;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Expediente.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.titulo)) {
        this.titulo = data().deepCopy(fields()[0].schema(), other.titulo);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.subtitulo)) {
        this.subtitulo = data().deepCopy(fields()[1].schema(), other.subtitulo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.documentos)) {
        this.documentos = data().deepCopy(fields()[2].schema(), other.documentos);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Expediente instance
     * @param other The existing instance to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Expediente other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.titulo)) {
        this.titulo = data().deepCopy(fields()[0].schema(), other.titulo);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subtitulo)) {
        this.subtitulo = data().deepCopy(fields()[1].schema(), other.subtitulo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.documentos)) {
        this.documentos = data().deepCopy(fields()[2].schema(), other.documentos);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'titulo' field.
      * @return The value.
      */
    public java.lang.String getTitulo() {
      return titulo;
    }


    /**
      * Sets the value of the 'titulo' field.
      * @param value The value of 'titulo'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Expediente.Builder setTitulo(java.lang.String value) {
      validate(fields()[0], value);
      this.titulo = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'titulo' field has been set.
      * @return True if the 'titulo' field has been set, false otherwise.
      */
    public boolean hasTitulo() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'titulo' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Expediente.Builder clearTitulo() {
      titulo = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subtitulo' field.
      * @return The value.
      */
    public java.lang.String getSubtitulo() {
      return subtitulo;
    }


    /**
      * Sets the value of the 'subtitulo' field.
      * @param value The value of 'subtitulo'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Expediente.Builder setSubtitulo(java.lang.String value) {
      validate(fields()[1], value);
      this.subtitulo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subtitulo' field has been set.
      * @return True if the 'subtitulo' field has been set, false otherwise.
      */
    public boolean hasSubtitulo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subtitulo' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Expediente.Builder clearSubtitulo() {
      subtitulo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentos' field.
      * @return The value.
      */
    public java.util.List<pe.gob.congreso.pl.data.Documento> getDocumentos() {
      return documentos;
    }


    /**
      * Sets the value of the 'documentos' field.
      * @param value The value of 'documentos'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Expediente.Builder setDocumentos(java.util.List<pe.gob.congreso.pl.data.Documento> value) {
      validate(fields()[2], value);
      this.documentos = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'documentos' field has been set.
      * @return True if the 'documentos' field has been set, false otherwise.
      */
    public boolean hasDocumentos() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'documentos' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Expediente.Builder clearDocumentos() {
      documentos = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Expediente build() {
      try {
        Expediente record = new Expediente();
        record.titulo = fieldSetFlags()[0] ? this.titulo : (java.lang.String) defaultValue(fields()[0]);
        record.subtitulo = fieldSetFlags()[1] ? this.subtitulo : (java.lang.String) defaultValue(fields()[1]);
        record.documentos = fieldSetFlags()[2] ? this.documentos : (java.util.List<pe.gob.congreso.pl.data.Documento>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Expediente>
    WRITER$ = (org.apache.avro.io.DatumWriter<Expediente>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Expediente>
    READER$ = (org.apache.avro.io.DatumReader<Expediente>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.titulo == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.titulo);
    }

    if (this.subtitulo == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.subtitulo);
    }

    long size0 = this.documentos.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (pe.gob.congreso.pl.data.Documento e0: this.documentos) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 0) {
        in.readNull();
        this.titulo = null;
      } else {
        this.titulo = in.readString();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.subtitulo = null;
      } else {
        this.subtitulo = in.readString();
      }

      long size0 = in.readArrayStart();
      java.util.List<pe.gob.congreso.pl.data.Documento> a0 = this.documentos;
      if (a0 == null) {
        a0 = new SpecificData.Array<pe.gob.congreso.pl.data.Documento>((int)size0, SCHEMA$.getField("documentos").schema());
        this.documentos = a0;
      } else a0.clear();
      SpecificData.Array<pe.gob.congreso.pl.data.Documento> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<pe.gob.congreso.pl.data.Documento>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          pe.gob.congreso.pl.data.Documento e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new pe.gob.congreso.pl.data.Documento();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 0) {
            in.readNull();
            this.titulo = null;
          } else {
            this.titulo = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.subtitulo = null;
          } else {
            this.subtitulo = in.readString();
          }
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<pe.gob.congreso.pl.data.Documento> a0 = this.documentos;
          if (a0 == null) {
            a0 = new SpecificData.Array<pe.gob.congreso.pl.data.Documento>((int)size0, SCHEMA$.getField("documentos").schema());
            this.documentos = a0;
          } else a0.clear();
          SpecificData.Array<pe.gob.congreso.pl.data.Documento> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<pe.gob.congreso.pl.data.Documento>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              pe.gob.congreso.pl.data.Documento e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new pe.gob.congreso.pl.data.Documento();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










