/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pe.gob.congreso.pl.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Ley extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5152496374993194828L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Ley\",\"namespace\":\"pe.gob.congreso.pl.data\",\"fields\":[{\"name\":\"numero\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"titulo\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"sumilla\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Ley> ENCODER =
      new BinaryMessageEncoder<Ley>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Ley> DECODER =
      new BinaryMessageDecoder<Ley>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Ley> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Ley> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Ley> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Ley>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Ley to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Ley from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Ley instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Ley fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String numero;
   private java.lang.String titulo;
   private java.lang.String sumilla;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Ley() {}

  /**
   * All-args constructor.
   * @param numero The new value for numero
   * @param titulo The new value for titulo
   * @param sumilla The new value for sumilla
   */
  public Ley(java.lang.String numero, java.lang.String titulo, java.lang.String sumilla) {
    this.numero = numero;
    this.titulo = titulo;
    this.sumilla = sumilla;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return numero;
    case 1: return titulo;
    case 2: return sumilla;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: numero = value$ != null ? value$.toString() : null; break;
    case 1: titulo = value$ != null ? value$.toString() : null; break;
    case 2: sumilla = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'numero' field.
   * @return The value of the 'numero' field.
   */
  public java.lang.String getNumero() {
    return numero;
  }


  /**
   * Sets the value of the 'numero' field.
   * @param value the value to set.
   */
  public void setNumero(java.lang.String value) {
    this.numero = value;
  }

  /**
   * Gets the value of the 'titulo' field.
   * @return The value of the 'titulo' field.
   */
  public java.lang.String getTitulo() {
    return titulo;
  }


  /**
   * Sets the value of the 'titulo' field.
   * @param value the value to set.
   */
  public void setTitulo(java.lang.String value) {
    this.titulo = value;
  }

  /**
   * Gets the value of the 'sumilla' field.
   * @return The value of the 'sumilla' field.
   */
  public java.lang.String getSumilla() {
    return sumilla;
  }


  /**
   * Sets the value of the 'sumilla' field.
   * @param value the value to set.
   */
  public void setSumilla(java.lang.String value) {
    this.sumilla = value;
  }

  /**
   * Creates a new Ley RecordBuilder.
   * @return A new Ley RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Ley.Builder newBuilder() {
    return new pe.gob.congreso.pl.data.Ley.Builder();
  }

  /**
   * Creates a new Ley RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Ley RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Ley.Builder newBuilder(pe.gob.congreso.pl.data.Ley.Builder other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Ley.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Ley.Builder(other);
    }
  }

  /**
   * Creates a new Ley RecordBuilder by copying an existing Ley instance.
   * @param other The existing instance to copy.
   * @return A new Ley RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Ley.Builder newBuilder(pe.gob.congreso.pl.data.Ley other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Ley.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Ley.Builder(other);
    }
  }

  /**
   * RecordBuilder for Ley instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Ley>
    implements org.apache.avro.data.RecordBuilder<Ley> {

    private java.lang.String numero;
    private java.lang.String titulo;
    private java.lang.String sumilla;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Ley.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.numero)) {
        this.numero = data().deepCopy(fields()[0].schema(), other.numero);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.titulo)) {
        this.titulo = data().deepCopy(fields()[1].schema(), other.titulo);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.sumilla)) {
        this.sumilla = data().deepCopy(fields()[2].schema(), other.sumilla);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Ley instance
     * @param other The existing instance to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Ley other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.numero)) {
        this.numero = data().deepCopy(fields()[0].schema(), other.numero);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.titulo)) {
        this.titulo = data().deepCopy(fields()[1].schema(), other.titulo);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sumilla)) {
        this.sumilla = data().deepCopy(fields()[2].schema(), other.sumilla);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'numero' field.
      * @return The value.
      */
    public java.lang.String getNumero() {
      return numero;
    }


    /**
      * Sets the value of the 'numero' field.
      * @param value The value of 'numero'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Ley.Builder setNumero(java.lang.String value) {
      validate(fields()[0], value);
      this.numero = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'numero' field has been set.
      * @return True if the 'numero' field has been set, false otherwise.
      */
    public boolean hasNumero() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'numero' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Ley.Builder clearNumero() {
      numero = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'titulo' field.
      * @return The value.
      */
    public java.lang.String getTitulo() {
      return titulo;
    }


    /**
      * Sets the value of the 'titulo' field.
      * @param value The value of 'titulo'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Ley.Builder setTitulo(java.lang.String value) {
      validate(fields()[1], value);
      this.titulo = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'titulo' field has been set.
      * @return True if the 'titulo' field has been set, false otherwise.
      */
    public boolean hasTitulo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'titulo' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Ley.Builder clearTitulo() {
      titulo = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sumilla' field.
      * @return The value.
      */
    public java.lang.String getSumilla() {
      return sumilla;
    }


    /**
      * Sets the value of the 'sumilla' field.
      * @param value The value of 'sumilla'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Ley.Builder setSumilla(java.lang.String value) {
      validate(fields()[2], value);
      this.sumilla = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sumilla' field has been set.
      * @return True if the 'sumilla' field has been set, false otherwise.
      */
    public boolean hasSumilla() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sumilla' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Ley.Builder clearSumilla() {
      sumilla = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Ley build() {
      try {
        Ley record = new Ley();
        record.numero = fieldSetFlags()[0] ? this.numero : (java.lang.String) defaultValue(fields()[0]);
        record.titulo = fieldSetFlags()[1] ? this.titulo : (java.lang.String) defaultValue(fields()[1]);
        record.sumilla = fieldSetFlags()[2] ? this.sumilla : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Ley>
    WRITER$ = (org.apache.avro.io.DatumWriter<Ley>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Ley>
    READER$ = (org.apache.avro.io.DatumReader<Ley>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.numero);

    if (this.titulo == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.titulo);
    }

    if (this.sumilla == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.sumilla);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.numero = in.readString();

      if (in.readIndex() != 0) {
        in.readNull();
        this.titulo = null;
      } else {
        this.titulo = in.readString();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.sumilla = null;
      } else {
        this.sumilla = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.numero = in.readString();
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.titulo = null;
          } else {
            this.titulo = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.sumilla = null;
          } else {
            this.sumilla = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










