/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pe.gob.congreso.pl.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Seguimiento extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 382343506066828546L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Seguimiento\",\"namespace\":\"pe.gob.congreso.pl.data\",\"fields\":[{\"name\":\"fecha\",\"type\":\"long\"},{\"name\":\"evento\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Seguimiento> ENCODER =
      new BinaryMessageEncoder<Seguimiento>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Seguimiento> DECODER =
      new BinaryMessageDecoder<Seguimiento>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Seguimiento> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Seguimiento> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Seguimiento> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Seguimiento>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Seguimiento to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Seguimiento from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Seguimiento instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Seguimiento fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long fecha;
   private java.lang.String evento;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Seguimiento() {}

  /**
   * All-args constructor.
   * @param fecha The new value for fecha
   * @param evento The new value for evento
   */
  public Seguimiento(java.lang.Long fecha, java.lang.String evento) {
    this.fecha = fecha;
    this.evento = evento;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fecha;
    case 1: return evento;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fecha = (java.lang.Long)value$; break;
    case 1: evento = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'fecha' field.
   * @return The value of the 'fecha' field.
   */
  public long getFecha() {
    return fecha;
  }


  /**
   * Sets the value of the 'fecha' field.
   * @param value the value to set.
   */
  public void setFecha(long value) {
    this.fecha = value;
  }

  /**
   * Gets the value of the 'evento' field.
   * @return The value of the 'evento' field.
   */
  public java.lang.String getEvento() {
    return evento;
  }


  /**
   * Sets the value of the 'evento' field.
   * @param value the value to set.
   */
  public void setEvento(java.lang.String value) {
    this.evento = value;
  }

  /**
   * Creates a new Seguimiento RecordBuilder.
   * @return A new Seguimiento RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Seguimiento.Builder newBuilder() {
    return new pe.gob.congreso.pl.data.Seguimiento.Builder();
  }

  /**
   * Creates a new Seguimiento RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Seguimiento RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Seguimiento.Builder newBuilder(pe.gob.congreso.pl.data.Seguimiento.Builder other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Seguimiento.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Seguimiento.Builder(other);
    }
  }

  /**
   * Creates a new Seguimiento RecordBuilder by copying an existing Seguimiento instance.
   * @param other The existing instance to copy.
   * @return A new Seguimiento RecordBuilder
   */
  public static pe.gob.congreso.pl.data.Seguimiento.Builder newBuilder(pe.gob.congreso.pl.data.Seguimiento other) {
    if (other == null) {
      return new pe.gob.congreso.pl.data.Seguimiento.Builder();
    } else {
      return new pe.gob.congreso.pl.data.Seguimiento.Builder(other);
    }
  }

  /**
   * RecordBuilder for Seguimiento instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Seguimiento>
    implements org.apache.avro.data.RecordBuilder<Seguimiento> {

    private long fecha;
    private java.lang.String evento;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Seguimiento.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fecha)) {
        this.fecha = data().deepCopy(fields()[0].schema(), other.fecha);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.evento)) {
        this.evento = data().deepCopy(fields()[1].schema(), other.evento);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Seguimiento instance
     * @param other The existing instance to copy.
     */
    private Builder(pe.gob.congreso.pl.data.Seguimiento other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.fecha)) {
        this.fecha = data().deepCopy(fields()[0].schema(), other.fecha);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.evento)) {
        this.evento = data().deepCopy(fields()[1].schema(), other.evento);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'fecha' field.
      * @return The value.
      */
    public long getFecha() {
      return fecha;
    }


    /**
      * Sets the value of the 'fecha' field.
      * @param value The value of 'fecha'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Seguimiento.Builder setFecha(long value) {
      validate(fields()[0], value);
      this.fecha = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fecha' field has been set.
      * @return True if the 'fecha' field has been set, false otherwise.
      */
    public boolean hasFecha() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fecha' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Seguimiento.Builder clearFecha() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'evento' field.
      * @return The value.
      */
    public java.lang.String getEvento() {
      return evento;
    }


    /**
      * Sets the value of the 'evento' field.
      * @param value The value of 'evento'.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Seguimiento.Builder setEvento(java.lang.String value) {
      validate(fields()[1], value);
      this.evento = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'evento' field has been set.
      * @return True if the 'evento' field has been set, false otherwise.
      */
    public boolean hasEvento() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'evento' field.
      * @return This builder.
      */
    public pe.gob.congreso.pl.data.Seguimiento.Builder clearEvento() {
      evento = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Seguimiento build() {
      try {
        Seguimiento record = new Seguimiento();
        record.fecha = fieldSetFlags()[0] ? this.fecha : (java.lang.Long) defaultValue(fields()[0]);
        record.evento = fieldSetFlags()[1] ? this.evento : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Seguimiento>
    WRITER$ = (org.apache.avro.io.DatumWriter<Seguimiento>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Seguimiento>
    READER$ = (org.apache.avro.io.DatumReader<Seguimiento>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.fecha);

    out.writeString(this.evento);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.fecha = in.readLong();

      this.evento = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.fecha = in.readLong();
          break;

        case 1:
          this.evento = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










